import { columns } from "@/components/custom/leads/columns";
import { DataTable } from "@/components/custom/leads/data-table";

async function fetchLeads(): Promise<LeadsData[]> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "1a@#12345678901",
          client_name: "John Doe",
          client_contact_no: "1234567890",
          client_email_id: "john@example.com",
          enquiry_type: "hotel booking",
          executive: "Jane Doe",
          package: "Goa",
          stage: "hot",
          status: "active",
        },
        {
          id: "2b$%12345678902",
          client_name: "Jane Doe",
          client_contact_no: "1234567890",
          client_email_id: "jane@example2.com",
          enquiry_type: "sight seeing",
          executive: "John Doe",
          package: "Paris",
          stage: "warm",
          status: "closed",
        },
        {
          id: "3c^&12345678903",
          client_name: "Alice Smith",
          client_contact_no: "1234567891",
          client_email_id: "alice@example.com",
          enquiry_type: "flight booking",
          executive: "Bob Brown",
          package: "New York",
          stage: "cold",
          status: "active",
        },
        {
          id: "4d*(12345678904",
          client_name: "Bob Brown",
          client_contact_no: "1234567892",
          client_email_id: "bob@example.com",
          enquiry_type: "other",
          executive: "Alice Smith",
          package: "Los Angeles",
          stage: "hot",
          status: "active",
        },
        {
          id: "5e)_12345678905",
          client_name: "Charlie Johnson",
          client_contact_no: "1234567893",
          client_email_id: "charlie@example.com",
          enquiry_type: "hotel booking",
          executive: "David Wilson",
          package: "Chicago",
          stage: "warm",
          status: "closed",
        },
        {
          id: "6f+!12345678906",
          client_name: "David Wilson",
          client_contact_no: "1234567894",
          client_email_id: "david@example.com",
          enquiry_type: "sight seeing",
          executive: "Charlie Johnson",
          package: "Miami",
          stage: "cold",
          status: "active",
        },
        {
          id: "7g@#12345678907",
          client_name: "Eve Davis",
          client_contact_no: "1234567895",
          client_email_id: "eve@example.com",
          enquiry_type: "flight booking",
          executive: "Frank Miller",
          package: "San Francisco",
          stage: "hot",
          status: "active",
        },
        {
          id: "8h$%12345678908",
          client_name: "Frank Miller",
          client_contact_no: "1234567896",
          client_email_id: "frank@example.com",
          enquiry_type: "sight seeing",
          executive: "Eve Davis",
          package: "Las Vegas",
          stage: "warm",
          status: "closed",
        },
        {
          id: "9i^&12345678909",
          client_name: "Grace Lee",
          client_contact_no: "1234567897",
          client_email_id: "grace@example.com",
          enquiry_type: "hotel booking",
          executive: "Hank Green",
          package: "Orlando",
          stage: "cold",
          status: "active",
        },
        {
          id: "10j*(12345678910",
          client_name: "Hank Green",
          client_contact_no: "1234567898",
          client_email_id: "hank@example.com",
          enquiry_type: "sight seeing",
          executive: "Grace Lee",
          package: "Seattle",
          stage: "hot",
          status: "active",
        },
        {
          id: "11k)_12345678911",
          client_name: "Ivy White",
          client_contact_no: "1234567899",
          client_email_id: "ivy@example.com",
          enquiry_type: "flight booking",
          executive: "Jack Black",
          package: "Boston",
          stage: "warm",
          status: "closed",
        },
        {
          id: "12l+!12345678912",
          client_name: "Jack Black",
          client_contact_no: "1234567800",
          client_email_id: "jack@example.com",
          enquiry_type: "transport",
          executive: "Ivy White",
          package: "Houston",
          stage: "cold",
          status: "active",
        },
        {
          id: "13m@#12345678913",
          client_name: "Karen Brown",
          client_contact_no: "1234567801",
          client_email_id: "karen@example.com",
          enquiry_type: "hotel booking",
          executive: "Leo King",
          package: "Phoenix",
          stage: "hot",
          status: "active",
        },
        {
          id: "14n$%12345678914",
          client_name: "Leo King",
          client_contact_no: "1234567802",
          client_email_id: "leo@example.com",
          enquiry_type: "sight seeing",
          executive: "Karen Brown",
          package: "Philadelphia",
          stage: "warm",
          status: "closed",
        },
        {
          id: "15o^&12345678915",
          client_name: "Mia Scott",
          client_contact_no: "1234567803",
          client_email_id: "mia@example.com",
          enquiry_type: "flight booking",
          executive: "Noah Clark",
          package: "San Diego",
          stage: "cold",
          status: "active",
        },
        {
          id: "16p*(12345678916",
          client_name: "Noah Clark",
          client_contact_no: "1234567804",
          client_email_id: "noah@example.com",
          enquiry_type: "flight booking",
          executive: "Mia Scott",
          package: "Dallas",
          stage: "hot",
          status: "active",
        },
        {
          id: "17q)_12345678917",
          client_name: "Olivia Lewis",
          client_contact_no: "1234567805",
          client_email_id: "olivia@example.com",
          enquiry_type: "hotel booking",
          executive: "Paul Walker",
          package: "San Jose",
          stage: "warm",
          status: "closed",
        },
        {
          id: "18r+!12345678918",
          client_name: "Paul Walker",
          client_contact_no: "1234567806",
          client_email_id: "paul@example.com",
          enquiry_type: "sight seeing",
          executive: "Olivia Lewis",
          package: "Austin",
          stage: "cold",
          status: "active",
        },
        {
          id: "19s@#12345678919",
          client_name: "Quinn Harris",
          client_contact_no: "1234567807",
          client_email_id: "quinn@example.com",
          enquiry_type: "flight booking",
          executive: "Rachel Adams",
          package: "Jacksonville",
          stage: "hot",
          status: "active",
        },
        {
          id: "20t$%12345678920",
          client_name: "Rachel Adams",
          client_contact_no: "1234567808",
          client_email_id: "rachel@example.com",
          enquiry_type: "transport",
          executive: "Quinn Harris",
          package: "Fort Worth",
          stage: "warm",
          status: "closed",
        },
        {
          id: "21u^&12345678921",
          client_name: "Sam Turner",
          client_contact_no: "1234567809",
          client_email_id: "sam@example.com",
          enquiry_type: "hotel booking",
          executive: "Tina Bell",
          package: "Columbus",
          stage: "cold",
          status: "active",
        },
        {
          id: "22v*(12345678922",
          client_name: "Tina Bell",
          client_contact_no: "1234567810",
          client_email_id: "tina@example.com",
          enquiry_type: "sight seeing",
          executive: "Sam Turner",
          package: "Charlotte",
          stage: "hot",
          status: "active",
        },
        {
          id: "23w)_12345678923",
          client_name: "Uma Wright",
          client_contact_no: "1234567811",
          client_email_id: "uma@example.com",
          enquiry_type: "flight booking",
          executive: "Victor Young",
          package: "Indianapolis",
          stage: "warm",
          status: "closed",
        },
        {
          id: "24x+!12345678924",
          client_name: "Victor Young",
          client_contact_no: "1234567812",
          client_email_id: "victor@example.com",
          enquiry_type: "hotel booking",
          executive: "Uma Wright",
          package: "San Antonio",
          stage: "cold",
          status: "active",
        },
        {
          id: "25y@#12345678925",
          client_name: "Wendy Harris",
          client_contact_no: "1234567813",
          client_email_id: "wendy@example.com",
          enquiry_type: "sight seeing",
          executive: "Xander King",
          package: "Denver",
          stage: "hot",
          status: "active",
        },
        {
          id: "26z$%12345678926",
          client_name: "Xander King",
          client_contact_no: "1234567814",
          client_email_id: "xander@example.com",
          enquiry_type: "flight booking",
          executive: "Wendy Harris",
          package: "Washington",
          stage: "warm",
          status: "closed",
        },
        {
          id: "27a^&12345678927",
          client_name: "Yara Lee",
          client_contact_no: "1234567815",
          client_email_id: "yara@example.com",
          enquiry_type: "hotel booking",
          executive: "Zane Scott",
          package: "Boston",
          stage: "cold",
          status: "active",
        },
        {
          id: "28b*(12345678928",
          client_name: "Zane Scott",
          client_contact_no: "1234567816",
          client_email_id: "zane@example.com",
          enquiry_type: "sight seeing",
          executive: "Yara Lee",
          package: "El Paso",
          stage: "hot",
          status: "active",
        },
        {
          id: "29c)_12345678929",
          client_name: "Amy Brown",
          client_contact_no: "1234567817",
          client_email_id: "amy@example.com",
          enquiry_type: "flight booking",
          executive: "Brian Clark",
          package: "Detroit",
          stage: "warm",
          status: "closed",
        },
        {
          id: "30d+!12345678930",
          client_name: "Brian Clark",
          client_contact_no: "1234567818",
          client_email_id: "brian@example.com",
          enquiry_type: "hotel booking",
          executive: "Amy Brown",
          package: "Nashville",
          stage: "cold",
          status: "active",
        },
        {
          id: "31e@#12345678931",
          client_name: "Cathy Davis",
          client_contact_no: "1234567819",
          client_email_id: "cathy@example.com",
          enquiry_type: "sight seeing",
          executive: "David Evans",
          package: "Memphis",
          stage: "hot",
          status: "active",
        },
        {
          id: "32f$%12345678932",
          client_name: "David Evans",
          client_contact_no: "1234567820",
          client_email_id: "david@example.com",
          enquiry_type: "flight booking",
          executive: "Cathy Davis",
          package: "Louisville",
          stage: "warm",
          status: "closed",
        },
        {
          id: "33g^&12345678933",
          client_name: "Eva Foster",
          client_contact_no: "1234567821",
          client_email_id: "eva@example.com",
          enquiry_type: "hotel booking",
          executive: "Frank Green",
          package: "Baltimore",
          stage: "cold",
          status: "active",
        },
        {
          id: "34h*(12345678934",
          client_name: "Frank Green",
          client_contact_no: "1234567822",
          client_email_id: "frank@example.com",
          enquiry_type: "sight seeing",
          executive: "Eva Foster",
          package: "Milwaukee",
          stage: "hot",
          status: "active",
        },
        {
          id: "35i)_12345678935",
          client_name: "Grace Harris",
          client_contact_no: "1234567823",
          client_email_id: "grace@example.com",
          enquiry_type: "flight booking",
          executive: "Henry Johnson",
          package: "Albuquerque",
          stage: "warm",
          status: "closed",
        },
        {
          id: "36j+!12345678936",
          client_name: "Henry Johnson",
          client_contact_no: "1234567824",
          client_email_id: "henry@example.com",
          enquiry_type: "hotel booking",
          executive: "Grace Harris",
          package: "Tucson",
          stage: "cold",
          status: "active",
        },
        {
          id: "37k@#12345678937",
          client_name: "Ivy King",
          client_contact_no: "1234567825",
          client_email_id: "ivy@example.com",
          enquiry_type: "sight seeing",
          executive: "Jack Lee",
          package: "Fresno",
          stage: "hot",
          status: "active",
        },
        {
          id: "38l$%12345678938",
          client_name: "Jack Lee",
          client_contact_no: "1234567826",
          client_email_id: "jack@example.com",
          enquiry_type: "flight booking",
          executive: "Ivy King",
          package: "Sacramento",
          stage: "warm",
          status: "closed",
        },
        {
          id: "39m^&12345678939",
          client_name: "Karen Miller",
          client_contact_no: "1234567827",
          client_email_id: "karen@example.com",
          enquiry_type: "hotel booking",
          executive: "Leo Nelson",
          package: "Kansas City",
          stage: "cold",
          status: "active",
        },
        {
          id: "40n*(12345678940",
          client_name: "Leo Nelson",
          client_contact_no: "1234567828",
          client_email_id: "leo@example.com",
          enquiry_type: "sight seeing",
          executive: "Karen Miller",
          package: "Mesa",
          stage: "hot",
          status: "active",
        },
        {
          id: "41o)_12345678941",
          client_name: "Mia Owens",
          client_contact_no: "1234567829",
          client_email_id: "mia@example.com",
          enquiry_type: "flight booking",
          executive: "Noah Parker",
          package: "Atlanta",
          stage: "warm",
          status: "closed",
        },
        {
          id: "42p+!12345678942",
          client_name: "Noah Parker",
          client_contact_no: "1234567830",
          client_email_id: "noah@example.com",
          enquiry_type: "hotel booking",
          executive: "Mia Owens",
          package: "Omaha",
          stage: "cold",
          status: "active",
        },
        {
          id: "43q@#12345678943",
          client_name: "Olivia Quinn",
          client_contact_no: "1234567831",
          client_email_id: "olivia@example.com",
          enquiry_type: "sight seeing",
          executive: "Paul Roberts",
          package: "Colorado Springs",
          stage: "hot",
          status: "active",
        },
        {
          id: "44r$%12345678944",
          client_name: "Paul Roberts",
          client_contact_no: "1234567832",
          client_email_id: "paul@example.com",
          enquiry_type: "flight booking",
          executive: "Olivia Quinn",
          package: "Raleigh",
          stage: "warm",
          status: "closed",
        },
        {
          id: "45s^&12345678945",
          client_name: "Quinn Smith",
          client_contact_no: "1234567833",
          client_email_id: "quinn@example.com",
          enquiry_type: "hotel booking",
          executive: "Rachel Taylor",
          package: "Miami",
          stage: "cold",
          status: "active",
        },
        {
          id: "46t*(12345678946",
          client_name: "Rachel Taylor",
          client_contact_no: "1234567834",
          client_email_id: "rachel@example.com",
          enquiry_type: "sight seeing",
          executive: "Quinn Smith",
          package: "Virginia Beach",
          stage: "hot",
          status: "active",
        },
        {
          id: "47u)_12345678947",
          client_name: "Sam Turner",
          client_contact_no: "1234567835",
          client_email_id: "sam@example.com",
          enquiry_type: "flight booking",
          executive: "Tina Bell",
          package: "Oakland",
          stage: "warm",
          status: "closed",
        },
        {
          id: "48v+!12345678948",
          client_name: "Tina Bell",
          client_contact_no: "1234567836",
          client_email_id: "tina@example.com",
          enquiry_type: "hotel booking",
          executive: "Sam Turner",
          package: "Minneapolis",
          stage: "cold",
          status: "active",
        },
        {
          id: "49w@#12345678949",
          client_name: "Uma Wright",
          client_contact_no: "1234567837",
          client_email_id: "uma@example.com",
          enquiry_type: "sight seeing",
          executive: "Victor Young",
          package: "Tulsa",
          stage: "hot",
          status: "active",
        },
        {
          id: "50x$%12345678950",
          client_name: "Victor Young",
          client_contact_no: "1234567838",
          client_email_id: "victor@example.com",
          enquiry_type: "flight booking",
          executive: "Uma Wright",
          package: "Arlington",
          stage: "warm",
          status: "closed",
        },
        {
          id: "51y^&12345678951",
          client_name: "Wendy Harris",
          client_contact_no: "1234567839",
          client_email_id: "wendy@example.com",
          enquiry_type: "hotel booking",
          executive: "Xander King",
          package: "New Orleans",
          stage: "cold",
          status: "active",
        },
        {
          id: "52z*(12345678952",
          client_name: "Xander King",
          client_contact_no: "1234567840",
          client_email_id: "xander@example.com",
          enquiry_type: "sight seeing",
          executive: "Wendy Harris",
          package: "Wichita",
          stage: "hot",
          status: "active",
        },
        {
          id: "53a@#12345678953",
          client_name: "Yara Lee",
          client_contact_no: "1234567841",
          client_email_id: "yara@example.com",
          enquiry_type: "flight booking",
          executive: "Zane Scott",
          package: "Boston",
          stage: "warm",
          status: "closed",
        },
        {
          id: "54b$%12345678954",
          client_name: "Zane Scott",
          client_contact_no: "1234567842",
          client_email_id: "zane@example.com",
          enquiry_type: "hotel booking",
          executive: "Yara Lee",
          package: "El Paso",
          stage: "cold",
          status: "active",
        },
        {
          id: "55c^&12345678955",
          client_name: "Amy Brown",
          client_contact_no: "1234567843",
          client_email_id: "amy@example.com",
          enquiry_type: "sight seeing",
          executive: "Brian Clark",
          package: "Detroit",
          stage: "hot",
          status: "active",
        },
        {
          id: "56d*(12345678956",
          client_name: "Brian Clark",
          client_contact_no: "1234567844",
          client_email_id: "brian@example.com",
          enquiry_type: "flight booking",
          executive: "Amy Brown",
          package: "Nashville",
          stage: "warm",
          status: "closed",
        },
        {
          id: "57e)_12345678957",
          client_name: "Cathy Davis",
          client_contact_no: "1234567845",
          client_email_id: "cathy@example.com",
          enquiry_type: "hotel booking",
          executive: "David Evans",
          package: "Memphis",
          stage: "cold",
          status: "active",
        },
        {
          id: "58f+!12345678958",
          client_name: "David Evans",
          client_contact_no: "1234567846",
          client_email_id: "david@example.com",
          enquiry_type: "sight seeing",
          executive: "Cathy Davis",
          package: "Louisville",
          stage: "hot",
          status: "active",
        },
        {
          id: "59g@#12345678959",
          client_name: "Eva Foster",
          client_contact_no: "1234567847",
          client_email_id: "eva@example.com",
          enquiry_type: "flight booking",
          executive: "Frank Green",
          package: "Baltimore",
          stage: "warm",
          status: "closed",
        },
        {
          id: "60h$%12345678960",
          client_name: "Frank Green",
          client_contact_no: "1234567848",
          client_email_id: "frank@example.com",
          enquiry_type: "hotel booking",
          executive: "Eva Foster",
          package: "Milwaukee",
          stage: "cold",
          status: "active",
        },
        {
          id: "61i^&12345678961",
          client_name: "Grace Harris",
          client_contact_no: "1234567849",
          client_email_id: "grace@example.com",
          enquiry_type: "sight seeing",
          executive: "Henry Johnson",
          package: "Albuquerque",
          stage: "hot",
          status: "active",
        },
        {
          id: "62j*(12345678962",
          client_name: "Henry Johnson",
          client_contact_no: "1234567850",
          client_email_id: "henry@example.com",
          enquiry_type: "flight booking",
          executive: "Grace Harris",
          package: "Tucson",
          stage: "warm",
          status: "closed",
        },
        {
          id: "63k)_12345678963",
          client_name: "Ivy King",
          client_contact_no: "1234567851",
          client_email_id: "ivy@example.com",
          enquiry_type: "hotel booking",
          executive: "Jack Lee",
          package: "Fresno",
          stage: "cold",
          status: "active",
        },
        {
          id: "64l+!12345678964",
          client_name: "Jack Lee",
          client_contact_no: "1234567852",
          client_email_id: "jack@example.com",
          enquiry_type: "sight seeing",
          executive: "Ivy King",
          package: "Sacramento",
          stage: "hot",
          status: "active",
        },
        {
          id: "65m@#12345678965",
          client_name: "Karen Miller",
          client_contact_no: "1234567853",
          client_email_id: "karen@example.com",
          enquiry_type: "flight booking",
          executive: "Leo Nelson",
          package: "Kansas City",
          stage: "warm",
          status: "closed",
        },
        {
          id: "66n$%12345678966",
          client_name: "Leo Nelson",
          client_contact_no: "1234567854",
          client_email_id: "leo@example.com",
          enquiry_type: "hotel booking",
          executive: "Karen Miller",
          package: "Mesa",
          stage: "cold",
          status: "active",
        },
        {
          id: "67o^&12345678967",
          client_name: "Mia Owens",
          client_contact_no: "1234567855",
          client_email_id: "mia@example.com",
          enquiry_type: "sight seeing",
          executive: "Noah Parker",
          package: "Atlanta",
          stage: "hot",
          status: "active",
        },
        {
          id: "68p*(12345678968",
          client_name: "Noah Parker",
          client_contact_no: "1234567856",
          client_email_id: "noah@example.com",
          enquiry_type: "flight booking",
          executive: "Mia Owens",
          package: "Omaha",
          stage: "warm",
          status: "closed",
        },
        {
          id: "69q)_12345678969",
          client_name: "Olivia Quinn",
          client_contact_no: "1234567857",
          client_email_id: "olivia@example.com",
          enquiry_type: "hotel booking",
          executive: "Paul Roberts",
          package: "Colorado Springs",
          stage: "cold",
          status: "active",
        },
        {
          id: "70r+!12345678970",
          client_name: "Paul Roberts",
          client_contact_no: "1234567858",
          client_email_id: "paul@example.com",
          enquiry_type: "sight seeing",
          executive: "Olivia Quinn",
          package: "Raleigh",
          stage: "hot",
          status: "active",
        },
        {
          id: "71s@#12345678971",
          client_name: "Quinn Smith",
          client_contact_no: "1234567859",
          client_email_id: "quinn@example.com",
          enquiry_type: "flight booking",
          executive: "Rachel Taylor",
          package: "Miami",
          stage: "warm",
          status: "closed",
        },
        {
          id: "72t$%12345678972",
          client_name: "Rachel Taylor",
          client_contact_no: "1234567860",
          client_email_id: "rachel@example.com",
          enquiry_type: "hotel booking",
          executive: "Quinn Smith",
          package: "Virginia Beach",
          stage: "cold",
          status: "active",
        },
        {
          id: "73u^&12345678973",
          client_name: "Sam Turner",
          client_contact_no: "1234567861",
          client_email_id: "sam@example.com",
          enquiry_type: "sight seeing",
          executive: "Tina Bell",
          package: "Oakland",
          stage: "hot",
          status: "active",
        },
        {
          id: "74v*(12345678974",
          client_name: "Tina Bell",
          client_contact_no: "1234567862",
          client_email_id: "tina@example.com",
          enquiry_type: "flight booking",
          executive: "Sam Turner",
          package: "Minneapolis",
          stage: "warm",
          status: "closed",
        },
        {
          id: "75w)_12345678975",
          client_name: "Uma Wright",
          client_contact_no: "1234567863",
          client_email_id: "uma@example.com",
          enquiry_type: "hotel booking",
          executive: "Victor Young",
          package: "Tulsa",
          stage: "cold",
          status: "active",
        },

      ]);
    }, 1000);
  });
}

0;
export default async function page() {
  const leads = await fetchLeads();
  return (
    <>
      <div className="mx-auto">
        <DataTable columns={columns} data={leads} />
      </div>
    </>
  );
}
